jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}


server:
  port: 8080


fcm:
  key:
    path: ENC(u3He/Vry/W2Yv0lIZq6keAtj+QlVRmmarnqqQKbdxOA93T4XKT/L9A==)
    scope: ENC(aZmM4IMQuGgOE8FbyAqPz41NVwYeJhXgdaN/jrFE01Jwuj7ToOIoZv6Pp6xsbpbpjuF4g5QO0gk=)

spring:
  datasource:
    url: ENC(O8ytIxFrnwnqYnNa3XPnDz3+CPe0Rv6rcx4O6TadMbh7EdFe435B6ldT4KJtDsjea1nOQCg+G0tDECugVTRrwzMx+2rg55SkRa8iRpY+SjnBTKZjgtFmc0Ev9PMrKEXu)
    username: ENC(H81AMAIMb8TG9vYT1O0b2A==)
    password: ENC(odYBvxeQGCrnjJcrU8FfPPnI+XMAy6/A)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: com.example.restapimvc.querydsl.CustomPGDialect

server-url: https://test.rudderuni.com/user-infos/

  h2:
    console:
      enabled: false
      path: /console

  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: rudderverify@gmail.com
    password: ENC(ahvZfWw0s1T488hy8iokxniRZHbDAtqmHmG/hKbiIZU=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ENC(Bq5J5icpRMeR1pS5JZ36T/hHAeDjAsBt)
    port: 61613
    username: ENC(Fh/ZsnqAK+fQuORD/JNqsA==)
    password: ENC(nsM1itGQWPBdBosvDENCCQ==)

jwt:
  secret: ENC(YwBliokjkdmTR8ZBhwtrQDyDyy8NDIIeOKC1Xsff5VHwtmZ2F9HT3g4CILYHQigYzAF8JTPAogNlYhkRyyljbcu10iuEvRWBtjeMUIolKJNOZhdJ5HJ5pwhX1GO/uMm4TRq8EcJnUN1sFNVhEnnz1Q==)

password:
  secret: ENC(SuduKmAP5a+Xh7kWOwyq6W8cqv2jGIywrVbtj3yxvdA=)

aws:
  s3:
    image-bucket: ENC(OOKgTrqBQOjmTARJt9kRFHOt/nfOddSAhL94InLdLXwqcPkRttOATw==)
    region: ap-northeast-2
    access-key-id: ENC(QHhOtFo3PU6+xznfgJo3YHuBglKgv/k4fvwbhLbJY3Q=)
    secret-access-key: ENC(xZV/pJfloHs13GFlQbYDD14SH6KC56L2MPKK9itCDYAMOz+q/tr9jbODAmWyjSMhnNpwzhHfMQc=)
  cloud-front:
    url:
      high-quality-profile-image: ENC(bIQvhUGwlwVFFGzw4auvYJjfoBSlkyNrmczz8DYnRBl3EYSm8uwU+hMLzmLdKVpGbY+nHlmTr4xWEEoy73qsZA==)
      preview-profile-image: ENC(789tqAtbft19agxcYos04rlPeSzz4Qu+Og1p924PJlfCmqmm9B3vXWUhJcyq/fgsQByN1hzPlMnPluehbczvIxlvTphy5WiM)

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

cloud-front:
  url:
    post-image: ENC(h17vZyscy5+AKY7sfuOTdk9oM4WGOlrW95Q+RiOFMAELbX7/dfFPaVrD9Bh+P/YO)
    profile-image-preview: ENC(Qmx949ysNK61i1n27cFNXd3H0lWGS2OZzRziUSNrgggcJR7oWCTfGNl3iPfYizniBcWQL4IMu1761J5iotcUGHTqZj+HWeZT)

square:
  access-token: ENC(A6cxITK2TarZau6HtKTRWINOsGZu0xyz7h1u3ColyU4XMei6bEcwN6PsB0D5k5G6nK7ztFsLAtGjI9Z+BDZLwr7VtTbOiiDVJ2x6ZxowhyY=)