
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  datasource:
    url: ENC(O8ytIxFrnwnqYnNa3XPnDz3+CPe0Rv6rcx4O6TadMbh7EdFe435B6ldT4KJtDsjea1nOQCg+G0tDECugVTRrwzMx+2rg55SkRa8iRpY+SjnBTKZjgtFmc0Ev9PMrKEXu)
    username: ENC(H81AMAIMb8TG9vYT1O0b2A==)
    password: ENC(odYBvxeQGCrnjJcrU8FfPPnI+XMAy6/A)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true



  h2:
    console:
      enabled: false
      path: /console

jwt:
  secret: ENC(YwBliokjkdmTR8ZBhwtrQDyDyy8NDIIeOKC1Xsff5VHwtmZ2F9HT3g4CILYHQigYzAF8JTPAogNlYhkRyyljbcu10iuEvRWBtjeMUIolKJNOZhdJ5HJ5pwhX1GO/uMm4TRq8EcJnUN1sFNVhEnnz1Q==)

password:
  secret: ENC(SuduKmAP5a+Xh7kWOwyq6W8cqv2jGIywrVbtj3yxvdA=)

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
